---
- name: Set HTTP port in Jenkins config.
  lineinfile:
    backrefs: yes
    dest: /etc/sysconfig/jenkins
    regexp: '^JENKINS_PORT='
    line: 'JENKINS_PORT={{ jenkins_port }}'
  notify: restart jenkins

- name: Jenkins - configure | Turn off Jenkins setup wizard
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: '^JENKINS_JAVA_OPTIONS='
    line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
  notify: restart jenkins