---
- name: Add jenkins repository.
  yum_repository:
    name: jenkins
    description: Jenkins
    baseurl: http://pkg.jenkins.io/redhat
    gpgkey: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    gpgcheck: yes
    enabled: no

- name: Ensure jenkins is installed.
  yum:
    name: jenkins
    enablerepo: jenkins
    state: installed